Update CheckandAddMembers.yml

diff --git a/.github/workflows/CheckandAddMembers.yml b/.github/workflows/CheckandAddMembers.yml
--- a/.github/workflows/CheckandAddMembers.yml
+++ b/.github/workflows/CheckandAddMembers.yml
@@ -32,19 +32,18 @@ jobs:
           USERNAME="$GITHUB_ID"
           TOKEN="${{ secrets.API_TOKEN }}"
           
-          # Make request to GitHub API
-          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $TOKEN" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/$ORG_NAME/members/$USERNAME")
+          # Attempt to add the user to the team
+          response=$(gh team add --team $MY_TEAM --member $USERNAME 2>&1)
 
           # Check Response Status
-          if [ $response -eq 204 ]; then
-            echo "$USERNAME is not found in $ORG_NAME. Adding $USERNAME to $MY_TEAM." > comment.md
-            gh team add --team $MY_TEAM --member $USERNAME
+          if [ $? -eq 0 ]; then
+            echo "$USERNAME is not a member of $ORG_NAME. Adding $USERNAME to $MY_TEAM." > comment.md
             gh issue comment ${{ github.event.issue.number }} --body-file=comment.md
-          elif [ $response -eq 404 ]; then
-            echo "$USERNAME is not member of $ORG_NAME." > comment.md
+          elif [[ $response == *"HTTP 404"* ]]; then
+            echo "$USERNAME is not a member of $ORG_NAME." > comment.md
             gh issue comment ${{ github.event.issue.number }} --body-file=comment.md
           else
-            echo "Error: HTTP status code $response"
+            echo "Error: $response"
           fi
         env:
           GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
